feature(#124): UserStatus 컴포넌트 구현
FRONTENDSCHOOL10/Pisa-s-4top pull request #137
Opened 2024-09-07 18:35 UTC by Suubiin

### feature(#124): UserStatus 컴포넌트 구현

### PR 유형

- [x] 새로운 기능 추가

### PR 체크 리스트

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트)

### 🔎 작업 내용

- title, count, ariaLabel 변수로 프롭 처리
- 스토리북 추가
  <br />

### 🔧 앞으로의 과제

- 내일 할 일을 적어주세요.
  <br />

### 이슈

resolves #124

2024-09-08 09:37 UTC, woolen-h approved these changes
검토 완료! 
여기도 브루잉 가이드에 쓰신것처럼 class 따로 관리하는거 어떠신가용!

2024-09-08 18:49 UTC, happyhye requested changes

2024-09-08 18:49 UTC, happyhye commented on src/components/User/UserStatus.tsx
> +         aria-label={ariaLabel}
title과 count가 시각적으로 노출되고 있기 때문에 스크린 리더 사용자도 해당 정보에 접근할 수 있습니다.
div 태그의 aria-label은 제거하시면 될 것 같아요~!

2024-09-09 01:23 UTC, minnje approved these changes

2024-09-09 06:05 UTC, happyhye approved these changes
검토 완료 👍

2024-09-09 06:05 UTC, merged