feat(#120): 리뷰 디테일 페이지 생성
FRONTENDSCHOOL10/Pisa-s-4top pull request #145
Opened 2024-09-08 11:43 UTC by woolen-h

### 제목 : feat(#120): 리뷰 디테일 페이지 생성

### PR 유형

- [x] 새로운 기능 추가

### PR 체크 리스트

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트)

### 🔎 작업 내용

- 리뷰 디테일 페이지 생성

### 🔧 앞으로의 과제

- 페이지 작업

### 이슈

resolves #120

2024-09-08 16:23 UTC, Suubiin commented on src/pages/Reviews/ReviewsDetailPage.tsx
> +import { ButtonError } from '@/components/Buttons/Buttons';
버튼 컴포넌트가 머지가 안된 상태라 머지된 후 수정 필요합니당!

2024-09-09 01:53 UTC, happyhye requested changes

2024-09-09 01:53 UTC, happyhye commented on src/pages/Reviews/ReviewsDetailPage.tsx
> +      <main className="flex flex-col items-center px-6">
main 태그 안에는 `<h1>` 태그를 필수로 넣어주셔야 합니다!

2024-09-09 03:09 UTC, minnje approved these changes
위 코멘트들 반영 부탁드립니다 🙌

2024-09-10 01:12 UTC, woolen-h commented on src/pages/Reviews/ReviewsDetailPage.tsx
> +import { ButtonError } from '@/components/Buttons/Buttons';
넵 확인했습니다!

2024-09-10 01:15 UTC, woolen-h commented on src/pages/Reviews/ReviewsDetailPage.tsx
> +      <main className="flex flex-col items-center px-6">
반영 완료했습니다! 감사합니다~

2024-09-10 01:19 UTC, Suubiin approved these changes

2024-09-10 01:19 UTC, suubiin commented on src/pages/Reviews/ReviewsDetailPage.tsx
> +            <h3>맛</h3>
폰트 스타일링을 h3 태그로 하신 거 맞을까용? mdn 문서에 '글씨 크기를 위해 제목 태그를 사용하지 마세요.' 라고 되어있는데 한 번 확인 부탁드립니당
[헤딩 태그 관련 mdn 문서](https://developer.mozilla.org/ko/docs/Web/HTML/Element/Heading_Elements)

2024-09-10 02:08 UTC, happyhye approved these changes
검토 완료 👍

2024-09-10 02:09 UTC, woolen-h commented on src/pages/Reviews/ReviewsDetailPage.tsx
> +            <h3>맛</h3>
<h2> 태그로 수정 반영했습니당! 감사합니다~

2024-09-10 02:09 UTC, merged